/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpt_chess;
import static cpt_chess.CPT_Chess.puzzle;
import static cpt_chess.CPT_Chess.puzzles_answers;
import static cpt_chess.Java_main_panel.CardLayout;
import static cpt_chess.Main_Java_Frame.parent;
import static cpt_chess.puzzles.puzzle_selected;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author lucas
 */
public class Chess_Puzzles_Hard extends javax.swing.JPanel {

    /**
     * Creates new form Chess_Puzzles_Hard
     */
    public Chess_Puzzles_Hard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hard_Title = new javax.swing.JLabel();
        Hard_1d = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Hard_3d = new javax.swing.JPanel();
        level_3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Hard_2d = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Hard_9f = new javax.swing.JPanel();
        level_4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(59, 61, 62));

        Hard_Title.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        Hard_Title.setForeground(new java.awt.Color(194, 194, 194));
        Hard_Title.setText("Hard");

        Hard_1d.setBackground(new java.awt.Color(51, 51, 51));
        Hard_1d.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hard_1d.setPreferredSize(new java.awt.Dimension(110, 110));
        Hard_1d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hard_1dMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(194, 194, 194));
        jLabel1.setText("1");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Unlockable at level 4 ");

        javax.swing.GroupLayout Hard_1dLayout = new javax.swing.GroupLayout(Hard_1d);
        Hard_1d.setLayout(Hard_1dLayout);
        Hard_1dLayout.setHorizontalGroup(
            Hard_1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hard_1dLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(Hard_1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hard_1dLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hard_1dLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );
        Hard_1dLayout.setVerticalGroup(
            Hard_1dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hard_1dLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Hard_3d.setBackground(new java.awt.Color(51, 51, 51));
        Hard_3d.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hard_3d.setPreferredSize(new java.awt.Dimension(110, 110));
        Hard_3d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hard_3dMouseClicked(evt);
            }
        });

        level_3.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        level_3.setForeground(new java.awt.Color(194, 194, 194));
        level_3.setText("3");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Unlockable at level 4");

        javax.swing.GroupLayout Hard_3dLayout = new javax.swing.GroupLayout(Hard_3d);
        Hard_3d.setLayout(Hard_3dLayout);
        Hard_3dLayout.setHorizontalGroup(
            Hard_3dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hard_3dLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(level_3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hard_3dLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        Hard_3dLayout.setVerticalGroup(
            Hard_3dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hard_3dLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(level_3)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );

        Hard_2d.setBackground(new java.awt.Color(51, 51, 51));
        Hard_2d.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hard_2d.setPreferredSize(new java.awt.Dimension(110, 110));
        Hard_2d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hard_2dMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(194, 194, 194));
        jLabel2.setText("2");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Unlockable at level 4");

        javax.swing.GroupLayout Hard_2dLayout = new javax.swing.GroupLayout(Hard_2d);
        Hard_2d.setLayout(Hard_2dLayout);
        Hard_2dLayout.setHorizontalGroup(
            Hard_2dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hard_2dLayout.createSequentialGroup()
                .addGroup(Hard_2dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Hard_2dLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(Hard_2dLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        Hard_2dLayout.setVerticalGroup(
            Hard_2dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hard_2dLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Hard_9f.setBackground(new java.awt.Color(51, 51, 51));
        Hard_9f.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hard_9f.setPreferredSize(new java.awt.Dimension(110, 110));
        Hard_9f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hard_9fMouseClicked(evt);
            }
        });

        level_4.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        level_4.setForeground(new java.awt.Color(194, 194, 194));
        level_4.setText("4");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Unlockable at level 4 ");

        javax.swing.GroupLayout Hard_9fLayout = new javax.swing.GroupLayout(Hard_9f);
        Hard_9f.setLayout(Hard_9fLayout);
        Hard_9fLayout.setHorizontalGroup(
            Hard_9fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hard_9fLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(Hard_9fLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(level_4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Hard_9fLayout.setVerticalGroup(
            Hard_9fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hard_9fLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(level_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("BACK");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(Hard_Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Hard_3d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hard_1d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Hard_2d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hard_9f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Hard_Title))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hard_1d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hard_2d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hard_3d, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hard_9f, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 1d and start puzzle code
    */
    private void Hard_1dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hard_1dMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 4){
            puzzle_selected = "1d";
            puzzle = cpt_chess.puzzles.puzzle_1d;
            puzzles_answers = cpt_chess.puzzles.puzzle_1d_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Hard_1dMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 3d and start puzzle code
    */
    private void Hard_3dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hard_3dMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 4){
            puzzle_selected = "3d";
            puzzle = cpt_chess.puzzles.puzzle_3d;
            puzzles_answers = cpt_chess.puzzles.puzzle_3d_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Hard_3dMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 2d and start puzzle code
    */
    private void Hard_2dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hard_2dMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 4){
            puzzle_selected = "2d";
            puzzle = cpt_chess.puzzles.puzzle_2d;
            puzzles_answers = cpt_chess.puzzles.puzzle_2d_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Hard_2dMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 9f and start puzzle code
    */
    private void Hard_9fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hard_9fMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 4){
            puzzle_selected = "9f";
            puzzle = cpt_chess.puzzles.puzzle_9f;
            puzzles_answers = cpt_chess.puzzles.puzzle_9f_answer;

            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Hard.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Hard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Hard_9fMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel as visible false and go to previous panel
    */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);

        CardLayout.show(parent, "card6");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hard_1d;
    private javax.swing.JPanel Hard_2d;
    private javax.swing.JPanel Hard_3d;
    private javax.swing.JPanel Hard_9f;
    private javax.swing.JLabel Hard_Title;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel level_3;
    private javax.swing.JLabel level_4;
    // End of variables declaration//GEN-END:variables
}
