/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cpt_chess;

import static cpt_chess.CPT_Chess.puzzle;
import static cpt_chess.CPT_Chess.puzzles_answers;
import static cpt_chess.puzzles.puzzle_selected;
import static cpt_chess.Java_main_panel.CardLayout;
import static cpt_chess.Main_Java_Frame.parent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lucas
 */
public class Chess_Puzzles_Easy extends javax.swing.JPanel {

    /**
     * Creates new form Chess_Puzzles_Easy
     */
    public Chess_Puzzles_Easy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Easy_Title = new javax.swing.JLabel();
        Easy_1c = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Easy_3c = new javax.swing.JPanel();
        level_3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Easy_2c2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Easy_4c = new javax.swing.JPanel();
        level_4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Easy_7c = new javax.swing.JPanel();
        level_7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Easy5c = new javax.swing.JPanel();
        level_5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Easy_6c = new javax.swing.JPanel();
        level_6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(59, 61, 62));
        setPreferredSize(new java.awt.Dimension(750, 500));

        Easy_Title.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        Easy_Title.setForeground(new java.awt.Color(194, 194, 194));
        Easy_Title.setText("Easy");

        Easy_1c.setBackground(new java.awt.Color(51, 51, 51));
        Easy_1c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy_1c.setPreferredSize(new java.awt.Dimension(110, 110));
        Easy_1c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Easy_1cMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(194, 194, 194));
        jLabel1.setText("1");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Unlockable at level 1 ");

        javax.swing.GroupLayout Easy_1cLayout = new javax.swing.GroupLayout(Easy_1c);
        Easy_1c.setLayout(Easy_1cLayout);
        Easy_1cLayout.setHorizontalGroup(
            Easy_1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Easy_1cLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(Easy_1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_1cLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_1cLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );
        Easy_1cLayout.setVerticalGroup(
            Easy_1cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Easy_1cLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Easy_3c.setBackground(new java.awt.Color(51, 51, 51));
        Easy_3c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy_3c.setPreferredSize(new java.awt.Dimension(110, 110));
        Easy_3c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Easy_3cMouseClicked(evt);
            }
        });

        level_3.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        level_3.setForeground(new java.awt.Color(194, 194, 194));
        level_3.setText("3");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Unlockable at level 2 ");

        javax.swing.GroupLayout Easy_3cLayout = new javax.swing.GroupLayout(Easy_3c);
        Easy_3c.setLayout(Easy_3cLayout);
        Easy_3cLayout.setHorizontalGroup(
            Easy_3cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Easy_3cLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(level_3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_3cLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        Easy_3cLayout.setVerticalGroup(
            Easy_3cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_3cLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(level_3)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );

        Easy_2c2.setBackground(new java.awt.Color(51, 51, 51));
        Easy_2c2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy_2c2.setPreferredSize(new java.awt.Dimension(110, 110));
        Easy_2c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Easy_2c2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(194, 194, 194));
        jLabel2.setText("2");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Unlockable at level 1 ");

        javax.swing.GroupLayout Easy_2c2Layout = new javax.swing.GroupLayout(Easy_2c2);
        Easy_2c2.setLayout(Easy_2c2Layout);
        Easy_2c2Layout.setHorizontalGroup(
            Easy_2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Easy_2c2Layout.createSequentialGroup()
                .addGroup(Easy_2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Easy_2c2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(Easy_2c2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        Easy_2c2Layout.setVerticalGroup(
            Easy_2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Easy_2c2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Easy_4c.setBackground(new java.awt.Color(51, 51, 51));
        Easy_4c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy_4c.setPreferredSize(new java.awt.Dimension(110, 110));
        Easy_4c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Easy_4cMouseClicked(evt);
            }
        });

        level_4.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        level_4.setForeground(new java.awt.Color(194, 194, 194));
        level_4.setText("4");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Unlockable at level 2 ");

        javax.swing.GroupLayout Easy_4cLayout = new javax.swing.GroupLayout(Easy_4c);
        Easy_4c.setLayout(Easy_4cLayout);
        Easy_4cLayout.setHorizontalGroup(
            Easy_4cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_4cLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(Easy_4cLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(level_4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Easy_4cLayout.setVerticalGroup(
            Easy_4cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_4cLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(level_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        Easy_7c.setBackground(new java.awt.Color(51, 51, 51));
        Easy_7c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy_7c.setPreferredSize(new java.awt.Dimension(110, 110));
        Easy_7c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Easy_7cMouseClicked(evt);
            }
        });

        level_7.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        level_7.setForeground(new java.awt.Color(194, 194, 194));
        level_7.setText("7");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Unlockable at level 2 ");

        javax.swing.GroupLayout Easy_7cLayout = new javax.swing.GroupLayout(Easy_7c);
        Easy_7c.setLayout(Easy_7cLayout);
        Easy_7cLayout.setHorizontalGroup(
            Easy_7cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_7cLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(Easy_7cLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(level_7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Easy_7cLayout.setVerticalGroup(
            Easy_7cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_7cLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(level_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18))
        );

        Easy5c.setBackground(new java.awt.Color(51, 51, 51));
        Easy5c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy5c.setPreferredSize(new java.awt.Dimension(110, 110));
        Easy5c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Easy5cMouseClicked(evt);
            }
        });

        level_5.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        level_5.setForeground(new java.awt.Color(194, 194, 194));
        level_5.setText("5");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Unlockable at level 2 ");

        javax.swing.GroupLayout Easy5cLayout = new javax.swing.GroupLayout(Easy5c);
        Easy5c.setLayout(Easy5cLayout);
        Easy5cLayout.setHorizontalGroup(
            Easy5cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy5cLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
            .addGroup(Easy5cLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(level_5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Easy5cLayout.setVerticalGroup(
            Easy5cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy5cLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(level_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(19, 19, 19))
        );

        Easy_6c.setBackground(new java.awt.Color(51, 51, 51));
        Easy_6c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Easy_6c.setPreferredSize(new java.awt.Dimension(110, 110));
        Easy_6c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Easy_6cMouseClicked(evt);
            }
        });

        level_6.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        level_6.setForeground(new java.awt.Color(194, 194, 194));
        level_6.setText("6");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Unlockable at level 2 ");

        javax.swing.GroupLayout Easy_6cLayout = new javax.swing.GroupLayout(Easy_6c);
        Easy_6c.setLayout(Easy_6cLayout);
        Easy_6cLayout.setHorizontalGroup(
            Easy_6cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Easy_6cLayout.createSequentialGroup()
                .addGroup(Easy_6cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Easy_6cLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(Easy_6cLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(level_6)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        Easy_6cLayout.setVerticalGroup(
            Easy_6cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Easy_6cLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(level_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(19, 19, 19))
        );

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("BACK");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Easy_1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(Easy_2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(Easy_3c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Easy_4c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252)
                        .addComponent(Easy_Title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(Easy5c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(Easy_6c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Easy_7c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Easy_Title)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Easy_1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Easy_2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Easy_3c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Easy_4c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Easy_7c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Easy_6c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Easy5c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 1c and start puzzle code
    */
    private void Easy_1cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy_1cMouseClicked

        if(cpt_chess.Experience.levelUp() >= 1){
            puzzle_selected = "1c";
            puzzle = cpt_chess.puzzles.puzzle_1c;
            puzzles_answers = cpt_chess.puzzles.puzzle_1c_answer;

            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Easy_1cMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 2c and start puzzle code
    */
    private void Easy_2c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy_2c2MouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 1){
            puzzle_selected = "2c";
            puzzle = cpt_chess.puzzles.puzzle_2c;
            puzzles_answers = cpt_chess.puzzles.puzzle_2c_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Easy_2c2MouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 3c and start puzzle code
    */
    private void Easy_3cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy_3cMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 2){
            puzzle_selected = "3c";
            puzzle = cpt_chess.puzzles.puzzle_3c;
            puzzles_answers = cpt_chess.puzzles.puzzle_3c_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Easy_3cMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 4c and start puzzle code
    */
    private void Easy_4cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy_4cMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 2){
            puzzle_selected = "4c";
            puzzle = cpt_chess.puzzles.puzzle_4c;
            puzzles_answers = cpt_chess.puzzles.puzzle_4c_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Easy_4cMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 5c and start puzzle code
    */
    private void Easy5cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy5cMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 2){
            puzzle_selected = "5c";
            puzzle = cpt_chess.puzzles.puzzle_5c;
            puzzles_answers = cpt_chess.puzzles.puzzle_5c_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Easy5cMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 6c and start puzzle code
    */
    private void Easy_6cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy_6cMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 2){
            puzzle_selected = "6c";
            puzzle = cpt_chess.puzzles.puzzle_6c;
            puzzles_answers = cpt_chess.puzzles.puzzle_6c_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Easy_6cMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: make puzzle and puzzle answer that of 7c and start puzzle code
    */
    private void Easy_7cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy_7cMouseClicked
        // TODO add your handling code here:
        if(cpt_chess.Experience.levelUp() >= 2){
            puzzle_selected = "7c";
            puzzle = cpt_chess.puzzles.puzzle_7c;
            puzzles_answers = cpt_chess.puzzles.puzzle_7c_answer;
            try {
                Puzzles_Main puzzle_main = new Puzzles_Main();
            } catch (IOException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Chess_Puzzles_Easy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Easy_7cMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel visible as false and go to previous panel
    */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        
        CardLayout.show(parent, "card6");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Easy5c;
    private javax.swing.JPanel Easy_1c;
    private javax.swing.JPanel Easy_2c2;
    private javax.swing.JPanel Easy_3c;
    private javax.swing.JPanel Easy_4c;
    private javax.swing.JPanel Easy_6c;
    private javax.swing.JPanel Easy_7c;
    private javax.swing.JLabel Easy_Title;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel level_3;
    private javax.swing.JLabel level_4;
    private javax.swing.JLabel level_5;
    private javax.swing.JLabel level_6;
    private javax.swing.JLabel level_7;
    // End of variables declaration//GEN-END:variables
}
