/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpt_chess;

import static cpt_chess.Java_main_panel.CardLayout;
import static cpt_chess.Lessons_Menu.lesson_num;
import static cpt_chess.Main_Java_Frame.parent;
import static cpt_chess.puzzles.Lesson_1_paths;
import static cpt_chess.puzzles.Lesson_2_paths;
import static cpt_chess.puzzles.Lesson_3_paths;
import static cpt_chess.puzzles.Lesson_4_paths;
import static cpt_chess.puzzles.Lesson_5_paths;
import static cpt_chess.puzzles.Lessons_All;
import static cpt_chess.puzzles.path;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author lucas
 */
public class Lesson_1_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Lesson_1_Panel
     */
    public Lesson_1_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lesson_img = new javax.swing.JLabel();
        Next_Button_Lesson_1 = new javax.swing.JButton();
        Back_Button_Lesson_1 = new javax.swing.JButton();

        if(lesson_num == 1){
            Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_1_paths[path]));
        }else if(lesson_num == 2){

            Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_2_paths[path]));
        }else if(lesson_num == 3){

            Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_3_paths[path]));
        }else if(lesson_num == 4){

            Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_4_paths[path]));
        }else{

            Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_5_paths[path]));
        }
        Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_1_paths[path]));

        Next_Button_Lesson_1.setText("NEXT");
        Next_Button_Lesson_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next_Button_Lesson_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_Button_Lesson_1ActionPerformed(evt);
            }
        });

        Back_Button_Lesson_1.setText("BACK");
        Back_Button_Lesson_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_Button_Lesson_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Button_Lesson_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lesson_img)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Back_Button_Lesson_1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 524, Short.MAX_VALUE)
                .addComponent(Next_Button_Lesson_1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lesson_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_Button_Lesson_1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_Button_Lesson_1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(416, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
    pre: java.awt.event.ActionEvent evt
    post: set icon to previous url in array
    post: if first url return to lessons menu
    */
    private void Back_Button_Lesson_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Button_Lesson_1ActionPerformed
        // TODO add your handling code here:
        if(path == 0){
            
            path = 0;
            
            if(lesson_num == 1){

                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_1_paths[path]));
            }else if(lesson_num == 2){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_2_paths[path]));
            }else if(lesson_num == 3){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_3_paths[path]));
            }else if(lesson_num == 4){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_4_paths[path]));
            }else{
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_5_paths[path]));
            }
            this.setVisible(false);

            CardLayout.show(parent, "card8");
            
            
        }else{
            
            path -= 1;
            if(lesson_num == 1){

                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_1_paths[path]));
            }else if(lesson_num == 2){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_2_paths[path]));
            }else if(lesson_num == 3){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_3_paths[path]));
            }else if(lesson_num == 4){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_4_paths[path]));
            }else{
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_5_paths[path]));
            }
        }
    }//GEN-LAST:event_Back_Button_Lesson_1ActionPerformed

    /*
    pre: java.awt.event.ActionEvent evt
    post: set icon to next url in array
    post: if final url return to lessons menu
    */
    private void Next_Button_Lesson_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_Button_Lesson_1ActionPerformed
        // TODO add your handling code here:
        
        if(Lessons_All[lesson_num-1].length - 1 == path){
            path = 0;
            this.setVisible(false);

            CardLayout.show(parent, "card8");
            if(lesson_num == 1){

                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_1_paths[path]));
            }else if(lesson_num == 2){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_2_paths[path]));
            }else if(lesson_num == 3){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_3_paths[path]));
            }else if(lesson_num == 4){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_4_paths[path]));
            }else{
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_5_paths[path]));
            }
            
        }else{
            path +=1;
            
            if(lesson_num == 1){

                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_1_paths[path]));
            }else if(lesson_num == 2){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_2_paths[path]));
            }else if(lesson_num == 3){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_3_paths[path]));
            }else if(lesson_num == 4){
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_4_paths[path]));
            }else{
                
                Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_5_paths[path]));
            }
        }
        
        
    }//GEN-LAST:event_Next_Button_Lesson_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button_Lesson_1;
    public static javax.swing.JLabel Lesson_img;
    private javax.swing.JButton Next_Button_Lesson_1;
    // End of variables declaration//GEN-END:variables
}
