/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpt_chess;

import static cpt_chess.Java_main_panel.CardLayout;
import static cpt_chess.Lesson_1_Panel.Lesson_img;
import static cpt_chess.Main_Java_Frame.parent;
import static cpt_chess.puzzles.Lesson_1_paths;
import static cpt_chess.puzzles.Lesson_2_paths;
import static cpt_chess.puzzles.Lesson_3_paths;
import static cpt_chess.puzzles.Lesson_4_paths;
import static cpt_chess.puzzles.Lesson_5_paths;
import static cpt_chess.puzzles.path;

/**
 *
 * @author lucas
 */
public class Lessons_Menu extends javax.swing.JPanel {

    /**
     * Creates new form Lessons_Menu
     */
    
    public static int lesson_num;
    
    public Lessons_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lessons_Title = new javax.swing.JLabel();
        Lesson_1_Bttn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lesson_2_Bttn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lessons_3_Bttn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lesson_5_Bttn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Lesson_4_Bttn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(59, 61, 62));
        setPreferredSize(new java.awt.Dimension(750, 500));

        Lessons_Title.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        Lessons_Title.setForeground(new java.awt.Color(194, 194, 194));
        Lessons_Title.setText("Lessons");

        Lesson_1_Bttn.setBackground(new java.awt.Color(51, 51, 51));
        Lesson_1_Bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lesson_1_Bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lesson_1_BttnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(194, 194, 194));
        jLabel1.setText("Lesson 1");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(194, 194, 194));
        jLabel2.setText("Chess Basics");

        javax.swing.GroupLayout Lesson_1_BttnLayout = new javax.swing.GroupLayout(Lesson_1_Bttn);
        Lesson_1_Bttn.setLayout(Lesson_1_BttnLayout);
        Lesson_1_BttnLayout.setHorizontalGroup(
            Lesson_1_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lesson_1_BttnLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(Lesson_1_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lesson_1_BttnLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        Lesson_1_BttnLayout.setVerticalGroup(
            Lesson_1_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lesson_1_BttnLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
        );

        Lesson_2_Bttn.setBackground(new java.awt.Color(51, 51, 51));
        Lesson_2_Bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lesson_2_Bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lesson_2_BttnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(194, 194, 194));
        jLabel3.setText("Lesson 2");

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(194, 194, 194));
        jLabel4.setText("Elements and Opening Priciples");

        javax.swing.GroupLayout Lesson_2_BttnLayout = new javax.swing.GroupLayout(Lesson_2_Bttn);
        Lesson_2_Bttn.setLayout(Lesson_2_BttnLayout);
        Lesson_2_BttnLayout.setHorizontalGroup(
            Lesson_2_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lesson_2_BttnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lesson_2_BttnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(46, 46, 46))
        );
        Lesson_2_BttnLayout.setVerticalGroup(
            Lesson_2_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lesson_2_BttnLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(40, 40, 40))
        );

        Lessons_3_Bttn.setBackground(new java.awt.Color(51, 51, 51));
        Lessons_3_Bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lessons_3_Bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lessons_3_BttnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(194, 194, 194));
        jLabel5.setText("Lesson 3");

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(194, 194, 194));
        jLabel6.setText("Basic Mating Patterns");

        javax.swing.GroupLayout Lessons_3_BttnLayout = new javax.swing.GroupLayout(Lessons_3_Bttn);
        Lessons_3_Bttn.setLayout(Lessons_3_BttnLayout);
        Lessons_3_BttnLayout.setHorizontalGroup(
            Lessons_3_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lessons_3_BttnLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lessons_3_BttnLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(37, 37, 37))
        );
        Lessons_3_BttnLayout.setVerticalGroup(
            Lessons_3_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lessons_3_BttnLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(40, 40, 40))
        );

        Lesson_5_Bttn.setBackground(new java.awt.Color(51, 51, 51));
        Lesson_5_Bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lesson_5_Bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lesson_5_BttnMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(194, 194, 194));
        jLabel7.setText("Lesson 5");

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(194, 194, 194));
        jLabel8.setText("Simple Openings and Defenses");

        javax.swing.GroupLayout Lesson_5_BttnLayout = new javax.swing.GroupLayout(Lesson_5_Bttn);
        Lesson_5_Bttn.setLayout(Lesson_5_BttnLayout);
        Lesson_5_BttnLayout.setHorizontalGroup(
            Lesson_5_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lesson_5_BttnLayout.createSequentialGroup()
                .addGroup(Lesson_5_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Lesson_5_BttnLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8))
                    .addGroup(Lesson_5_BttnLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Lesson_5_BttnLayout.setVerticalGroup(
            Lesson_5_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lesson_5_BttnLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(40, 40, 40))
        );

        Lesson_4_Bttn.setBackground(new java.awt.Color(51, 51, 51));
        Lesson_4_Bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lesson_4_Bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lesson_4_BttnMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(194, 194, 194));
        jLabel9.setText("Lesson 4");

        jLabel10.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(194, 194, 194));
        jLabel10.setText("Basic Tactics");

        javax.swing.GroupLayout Lesson_4_BttnLayout = new javax.swing.GroupLayout(Lesson_4_Bttn);
        Lesson_4_Bttn.setLayout(Lesson_4_BttnLayout);
        Lesson_4_BttnLayout.setHorizontalGroup(
            Lesson_4_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lesson_4_BttnLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(Lesson_4_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lesson_4_BttnLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        Lesson_4_BttnLayout.setVerticalGroup(
            Lesson_4_BttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lesson_4_BttnLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(40, 40, 40))
        );

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("BACK");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Lesson_4_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(Lesson_5_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Lesson_1_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(Lesson_2_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Lessons_3_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Lessons_Title)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Lessons_Title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lesson_1_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lesson_2_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lessons_3_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lesson_4_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lesson_5_Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel visible to false and display lessons_1 panel 
    post: set icon to Lesson_1_paths
    */
    private void Lesson_1_BttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lesson_1_BttnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_1_paths[path]));
        lesson_num = 1;
        CardLayout.show(parent, "card9");
        
    }//GEN-LAST:event_Lesson_1_BttnMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel visible to false and display previous panel
    */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);

        CardLayout.show(parent, "card5");
    }//GEN-LAST:event_jButton3ActionPerformed

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel visible to false and display lessons_1 panel 
    post: set icon to Lesson_2_paths
    */
    private void Lesson_2_BttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lesson_2_BttnMouseClicked
        // TODO add your handling code here:
        
        this.setVisible(false);
        Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_2_paths[path]));
        lesson_num = 2;
        CardLayout.show(parent, "card9");
        
    }//GEN-LAST:event_Lesson_2_BttnMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel visible to false and display lessons_1 panel 
    post: set icon to Lesson_3_paths
    */
    private void Lessons_3_BttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lessons_3_BttnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_3_paths[path]));
        lesson_num = 3;
        CardLayout.show(parent, "card9");
        
        
    }//GEN-LAST:event_Lessons_3_BttnMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel visible to false and display lessons_1 panel 
    post: set icon to Lesson_4_paths
    */
    private void Lesson_4_BttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lesson_4_BttnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_4_paths[path]));
        lesson_num = 4;
        CardLayout.show(parent, "card9");
        
    }//GEN-LAST:event_Lesson_4_BttnMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: set panel visible to false and display lessons_1 panel 
    post: set icon to Lesson_5_paths
    */
    private void Lesson_5_BttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lesson_5_BttnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Lesson_img.setIcon(new javax.swing.ImageIcon(Lesson_5_paths[path]));
        lesson_num = 5;
        CardLayout.show(parent, "card9");
    }//GEN-LAST:event_Lesson_5_BttnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lesson_1_Bttn;
    private javax.swing.JPanel Lesson_2_Bttn;
    private javax.swing.JPanel Lesson_4_Bttn;
    private javax.swing.JPanel Lesson_5_Bttn;
    private javax.swing.JPanel Lessons_3_Bttn;
    private javax.swing.JLabel Lessons_Title;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
