/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpt_chess;

import static cpt_chess.Java_main_panel.CardLayout;
import static cpt_chess.Main_Java_Frame.main_frame;
import static cpt_chess.Main_Java_Frame.parent;
import static cpt_chess.test_chess.Multiplayer;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lucas
 */
public class Single_Multiplayer_Prompt extends javax.swing.JPanel {

    /**
     * Creates new form Single_Multiplayer_Prompt
     */
    public Single_Multiplayer_Prompt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Panel = new javax.swing.JPanel();
        Single_Player_Panel = new javax.swing.JPanel();
        Single_Player_Label = new javax.swing.JLabel();
        Multiplayer_panel_select = new javax.swing.JPanel();
        Multiplayer_label = new javax.swing.JLabel();
        Back_Bttn_Single_Multiplayer_Prompt = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 490));

        Menu_Panel.setBackground(new java.awt.Color(59, 61, 62));
        Menu_Panel.setPreferredSize(new java.awt.Dimension(680, 470));

        Single_Player_Panel.setBackground(new java.awt.Color(65, 68, 70));
        Single_Player_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Single_Player_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Single_Player_PanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Single_Player_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Single_Player_PanelMouseExited(evt);
            }
        });

        Single_Player_Label.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Single_Player_Label.setForeground(new java.awt.Color(192, 192, 192));
        Single_Player_Label.setText("Single Player");

        javax.swing.GroupLayout Single_Player_PanelLayout = new javax.swing.GroupLayout(Single_Player_Panel);
        Single_Player_Panel.setLayout(Single_Player_PanelLayout);
        Single_Player_PanelLayout.setHorizontalGroup(
            Single_Player_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Single_Player_PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Single_Player_Label)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Single_Player_PanelLayout.setVerticalGroup(
            Single_Player_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Single_Player_PanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(Single_Player_Label)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        Multiplayer_panel_select.setBackground(new java.awt.Color(65, 68, 70));
        Multiplayer_panel_select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Multiplayer_panel_select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Multiplayer_panel_selectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Multiplayer_panel_selectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Multiplayer_panel_selectMouseExited(evt);
            }
        });

        Multiplayer_label.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Multiplayer_label.setForeground(new java.awt.Color(192, 192, 192));
        Multiplayer_label.setText("Multiplayer");

        javax.swing.GroupLayout Multiplayer_panel_selectLayout = new javax.swing.GroupLayout(Multiplayer_panel_select);
        Multiplayer_panel_select.setLayout(Multiplayer_panel_selectLayout);
        Multiplayer_panel_selectLayout.setHorizontalGroup(
            Multiplayer_panel_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Multiplayer_panel_selectLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(Multiplayer_label)
                .addGap(29, 29, 29))
        );
        Multiplayer_panel_selectLayout.setVerticalGroup(
            Multiplayer_panel_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Multiplayer_panel_selectLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(Multiplayer_label)
                .addGap(150, 150, 150))
        );

        Back_Bttn_Single_Multiplayer_Prompt.setBackground(new java.awt.Color(51, 51, 51));
        Back_Bttn_Single_Multiplayer_Prompt.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        Back_Bttn_Single_Multiplayer_Prompt.setForeground(new java.awt.Color(204, 204, 204));
        Back_Bttn_Single_Multiplayer_Prompt.setText("BACK");
        Back_Bttn_Single_Multiplayer_Prompt.setBorder(null);
        Back_Bttn_Single_Multiplayer_Prompt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_Bttn_Single_Multiplayer_Prompt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Bttn_Single_Multiplayer_PromptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_PanelLayout = new javax.swing.GroupLayout(Menu_Panel);
        Menu_Panel.setLayout(Menu_PanelLayout);
        Menu_PanelLayout.setHorizontalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(Single_Player_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(Multiplayer_panel_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Back_Bttn_Single_Multiplayer_Prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu_PanelLayout.setVerticalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Multiplayer_panel_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addComponent(Back_Bttn_Single_Multiplayer_Prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Single_Player_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
    pre: java.awt.event.MouseEvent evt
    post: set Single_Player_Panel background to light grey
    */
    private void Single_Player_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Single_Player_PanelMouseEntered
        // TODO add your handling code here:

        Single_Player_Panel.setBackground(new java.awt.Color(102, 102, 102));

    }//GEN-LAST:event_Single_Player_PanelMouseEntered

    /*
    pre: java.awt.event.MouseEvent evt
    post: set Single_Player_Panel background to original
    */
    private void Single_Player_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Single_Player_PanelMouseExited
        // TODO add your handling code here:

        Single_Player_Panel.setBackground(new java.awt.Color(65,68,70));

    }//GEN-LAST:event_Single_Player_PanelMouseExited

    /*
    pre: java.awt.event.MouseEvent evt
    post: set Multiplayer_panel_select background to light grey
    */
    private void Multiplayer_panel_selectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Multiplayer_panel_selectMouseEntered
        // TODO add your handling code here:

        Multiplayer_panel_select.setBackground(new java.awt.Color(102, 102, 102));

    }//GEN-LAST:event_Multiplayer_panel_selectMouseEntered

    /*
    pre: java.awt.event.MouseEvent evt
    post: set Multiplayer_panel_select background to original
    */
    private void Multiplayer_panel_selectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Multiplayer_panel_selectMouseExited
        // TODO add your handling code here:

        Multiplayer_panel_select.setBackground(new java.awt.Color(65,68,70));

    }//GEN-LAST:event_Multiplayer_panel_selectMouseExited

    /*
    pre: java.awt.event.MouseEvent evt
    post: set Multiplayer to "s"
    post: set panel visible false and show card4 in CardLayout
    */
    private void Single_Player_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Single_Player_PanelMouseClicked
        // TODO add your handling code here:
        
        Multiplayer = "s";
        this.setVisible(false);
                
        CardLayout.show(parent, "card4");
        
    }//GEN-LAST:event_Single_Player_PanelMouseClicked

    /*
    pre: java.awt.event.MouseEvent evt
    post: set Multiplayer to "m"
    post: removeAll from main_frame and run game
    */
    private void Multiplayer_panel_selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Multiplayer_panel_selectMouseClicked
        // TODO add your handling code here:
        
        Multiplayer = "m";
        cpt_chess.CPT_Chess.colour_select = "w";
        
        cpt_chess.Main_Game game;
        
        main_frame.getContentPane().removeAll();
        //main_frame.revalidate();
        
        try {
            game = new cpt_chess.Main_Game();
        } catch (IOException ex) {
            Logger.getLogger(Single_Multiplayer_Prompt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Single_Multiplayer_Prompt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Multiplayer_panel_selectMouseClicked

    /*
    pre: java.awt.event.ActionEvent evt
    post: set panel visible false and switch to previous panel
    */
    private void Back_Bttn_Single_Multiplayer_PromptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Bttn_Single_Multiplayer_PromptActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        CardLayout.show(parent, "card2");
    }//GEN-LAST:event_Back_Bttn_Single_Multiplayer_PromptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Bttn_Single_Multiplayer_Prompt;
    private javax.swing.JPanel Menu_Panel;
    private javax.swing.JLabel Multiplayer_label;
    private javax.swing.JPanel Multiplayer_panel_select;
    private javax.swing.JLabel Single_Player_Label;
    private javax.swing.JPanel Single_Player_Panel;
    // End of variables declaration//GEN-END:variables
}
